# Generated by Django 4.2.4 on 2023-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_alter_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
