# Generated by Django 4.2.4 on 2023-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0005_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ManyToManyField(blank=True, default='image.jpg', related_name='image', to='base_data.image'),
        ),
    ]
