# Generated by Django 4.2.4 on 2023-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0007_remove_card_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
